service: GethService
id: c897hnj-ijnfs67
configVersion: 1
command:
  - --mainnet
  - --state.scheme=path
  - --http
  - --http.api=eth,web3,net
  - --http.port=8545
  - --http.addr=0.0.0.0
  - --http.corsdomain=*
  - --http.vhosts=*
  - --ws
  - --ws.api=eth,net,web3
  - --ws.port=8546
  - --ws.addr=0.0.0.0
  - --ws.origins=*
  - --authrpc.port=8551
  - --authrpc.vhosts=*
  - --authrpc.addr=0.0.0.0
  - --authrpc.jwtsecret=/engine.jwt
  - --datadir=/opt/data/geth
  - --metrics
  - --metrics.expensive
  - --metrics.port=6060
  - --metrics.addr=0.0.0.0
  - --txlookuplimit=0
  - --cache=32768
entrypoint:
  - geth
env: {}
image: ethereum/client-go:v1.16.3
ports:
  - 0.0.0.0:8545:8545/tcp
  - 0.0.0.0:8546:8546/tcp
  - 0.0.0.0:30303:30303/tcp
  - 0.0.0.0:30303:30303/udp
user: root
autoupdate: true
network: mainnet
dependencies:
  executionClients: []
  consensusClients: []
  mevboost: []
  otherServices: []
