apiVersion: v1
kind: Service
metadata:
  name: app-dapp-service
  namespace: bubsy
spec:
  type: NodePort
  selector:
    app: app-dapp
  ports:
    - port: 5188
      targetPort: 5188
      nodePort: 30088
